var iceCreamJson = {
  "title": "Ice Cream Flavors",
  "explanation": "Those are the most popular Ice Cream Flavors according to the International Ice Cream Association. From those flavors, which ones are YOUR favorites?",
  "list": { "Vanilla" :{ "img": "./img/ice_cream/vanilla.jpg"},
            "Chocolate" :{ "img": "./img/ice_cream/chocolate.jpg"},
            "Strawberry" :{ "img": "./img/ice_cream/strawberry.jpg"},
            "Neapolitan" :{ "img": "./img/ice_cream/naepolitan.jpg"},
            "Chocolate chip" :{ "img": "./img/ice_cream/chocochip.jpg"},
            "Cookies and Cream" :{ "img": "./img/ice_cream/cookiecream.jpg"},
            "Cherry" :{ "img": "./img/ice_cream/cherry.jpg"},
            "Chocolate almond" :{ "img": "./img/ice_cream/almond.jpg"},
            "Pistachio" :{ "img": "./img/ice_cream/pistachio.jpg"},
            "Mint Chocolate" :{ "img": "./img/ice_cream/mint.jpg"}
          }
}

var pixarJson = {
  "title": "Pixar Films",
  "explanation": "Those are all the Pixar films released until the end of 2017. Rank the ones you watched and find out YOUR favourites!",
  "list": { "Toy Story": {"img": "./img/pixar/toys.jpg", "info":"<b>Year:</b> 1995"},
            "A Bug's Life": {"img": "./img/pixar/bugs.jpg", "info":"<b>Year:</b> 1998"},
            "Toy Story 2": {"img": "./img/pixar/toys2.jpg", "info":"<b>Year:</b> 1999"},
            "Monsters, Inc.": {"img": "./img/pixar/monsters.jpg", "info":"<b>Year:</b> 2001"},
            "Finding Nemo": {"img": "./img/pixar/nemo.jpg", "info":"<b>Year:</b> 2003"},
            "The Incredibles": {"img": "./img/pixar/incredibles.jpg", "info":"<b>Year:</b> 2004"},
            "Cars": {"img": "./img/pixar/cars.jpg", "info":"<b>Year:</b> 2006"},
            "Ratatouille": {"img": "./img/pixar/rata.jpg", "info":"<b>Year:</b> 2007"},
            "WALL-E": {"img": "./img/pixar/walle.jpg", "info":"<b>Year:</b> 2008"},
            "Up": {"img": "./img/pixar/up.jpg", "info":"<b>Year:</b> 2009"},
            "Toy Story 3": {"img": "./img/pixar/toys3.jpg", "info":"<b>Year:</b> 2010"},
            "Cars 2": {"img": "./img/pixar/cars2.jpg", "info":"<b>Year:</b> 2011"},
            "Brave": {"img": "./img/pixar/brave.jpg", "info":"<b>Year:</b> 2012"},
            "Monsters University": {"img": "./img/pixar/monsters2.jpg", "info":"<b>Year:</b> 2013"},
            "Inside Out": {"img": "./img/pixar/insideout.jpg", "info":"<b>Year:</b> 2015"},
            "The Good Dinosaur": {"img": "./img/pixar/dino.jpg", "info":"<b>Year:</b> 2015"},
            "Finding Dory": {"img": "./img/pixar/dory.jpg", "info":"<b>Year:</b> 2016"},
            "Cars 3": {"img": "./img/pixar/cars3.jpg", "info":"<b>Year:</b> 2017"},
            "Coco": {"img": "./img/pixar/coco.jpg", "info":"<b>Year:</b> 2017"},
          }
}

var goty2017json = {
  "title": "Games of 2017",
  "explanation": "Those are the 50 best reviewed games of 2017 according to Metacritic. Cross out the ones you did not play and find out your ranking for the year!<br>This list does not include games not originally released on 2017, so no ports, HD remasters, DLC or compilations. There are also only games with at least 20 reviews on one platform.<br><b><It might take a while until the whole list is sorted, be patient!/b>",
  "list": { "The Legend of Zelda: Breath of the Wild" : {"img": "./img/goty2017/zelda.jpg", "info": "Platforms: "},
            "Super Mario Odyssey" : {"img": "./img/goty2017/mario.jpg", "info": "Platforms: "},
            "Persona 5" : {"img": "./img/goty2017/persona.jpg", "info": "Platforms: "},
            "Divinity: Original Sin II" : {"img": "./img/goty2017/divinity2.jpg", "info": "Platforms: "},
            "What Remains of Edith Finch" : {"img": "./img/goty2017/finch.jpg", "info": "Platforms: "},
            "F1 2017" : {"img": "./img/goty2017/f1.jpg", "info": "Platforms: "},
            "Danganronpa V3: Killing Harmony" : {"img": "./img/goty2017/v3.jpg", "info": "Platforms: "},
            "Horizon Zero Dawn" : {"img": "./img/goty2017/horizon.jpg", "info": "Platforms: "},
            "Injustice 2" : {"img": "./img/goty2017/injustice.jpg", "info": "Platforms: "},
            "Wolfenstein II: The New Colossus" : {"img": "./img/goty2017/wolf2.jpg", "info": "Platforms: "},
            "NieR: Automata" : {"img": "./img/goty2017/nier.jpg", "info": "Platforms: "},
            "Cuphead" : {"img": "./img/goty2017/cuphead.jpg", "info": "Platforms: "},
            "SteamWorld Dig 2" : {"img": "./img/goty2017/steam2.jpg", "info": "Platforms: "},
            "Nex Machina" : {"img": "./img/goty2017/nex.jpg", "info": "Platforms: "},
            "Night in the Woods" : {"img": "./img/goty2017/woods.jpg", "info": "Platforms: "},
            "Nioh" : {"img": "./img/goty2017/nioh.jpg", "info": "Platforms: "},
            "Destiny 2" : {"img": "./img/goty2017/destiny2.jpg", "info": "Platforms: "},
            "Forza Motorsport 7" : {"img": "./img/goty2017/forza7.jpg", "info": "Platforms: "},
            "Splatoon 2" : {"img": "./img/goty2017/splatoon2.jpg", "info": "Platforms: "},
            "Total War: WARHAMMER II" : {"img": "./img/goty2017/totalhammer.jpg", "info": "Platforms: "},
            "Hollow Knight" : {"img": "./img/goty2017/hollow.jpg", "info": "Platforms: "},
            "Thimbleweed Park" : {"img": "./img/goty2017/thimbleweed.jpg", "info": "Platforms: "},
            "Resident Evil 7: biohazard" : {"img": "./img/goty2017/re7.jpg", "info": "Platforms: "},
            "Sonic Mania" : {"img": "./img/goty2017/sonicmania.jpg", "info": "Platforms: "},
            "Hellblade: Senua's Sacrifice" : {"img": "./img/goty2017/hellblade.jpg", "info": "Platforms: "},
            "DiRT 4" : {"img": "./img/goty2017/dirt4.jpg", "info": "Platforms: "},
            "Metroid: Samus Returns" : {"img": "./img/goty2017/metroid.jpg", "info": "Platforms: "},
            "Fire Emblem Echoes: Shadows of Valentia" : {"img": "./img/goty2017/fireemblem.jpg", "info": "Platforms: "},
            "The Evil Within 2" : {"img": "./img/goty2017/devilwithin2.jpg", "info": "Platforms: "},
            "Assassin's Creed Origins" : {"img": "./img/goty2017/acorigins.jpg", "info": "Platforms: "},
            "Project CARS 2" : {"img": "./img/goty2017/projectcars2.jpg", "info": "Platforms: "},
            "PlayerUnknown's Battlegrounds" : {"img": "./img/goty2017/pubg.jpg", "info": "Platforms: "},
            "Ys VIII: Lacrimosa of DANA" : {"img": "./img/goty2017/ysviii.jpg", "info": "Platforms: "},
            "Yakuza 0" : {"img": "./img/goty2017/yakuza0.jpg", "info": "Platforms: "},
            "MLB The Show 17" : {"img": "./img/goty2017/mlbshow.jpg", "info": "Platforms: "},
            "Mario + Rabbids: Kingdom Battle" : {"img": "./img/goty2017/mariorabbids.jpg", "info": "Platforms: "},
            "NBA 2K18" : {"img": "./img/goty2017/nba2k18.jpg", "info": "Platforms: "},
            "Pyre" : {"img": "./img/goty2017/pyre.jpg", "info": "Platforms: "},
            "Pokemon Ultra Sun/Moon" : {"img": "./img/goty2017/pokemonsm.jpg", "info": "Platforms: "},
            "South Park: The Fractured But Whole" : {"img": "./img/goty2017/southparkbutt.jpg", "info": "Platforms: "},
            "Tekken 7" : {"img": "./img/goty2017/tekken7.jpg", "info": "Platforms: "},
            "Shovel Knight: Specter of Torment" : {"img": "./img/goty2017/specter.jpg", "info": "Platforms: "},
            "Prey" : {"img": "./img/goty2017/prey.jpg", "info": "Platforms: "},
            "Battle Chasers: Nightwar" : {"img": "./img/goty2017/battlechasers.jpg", "info": "Platforms: "},
            "Hatsune Miku: Project Diva Future Tone" : {"img": "./img/goty2017/hatmik.jpg", "info": "Platforms: "},
            "The End Is Nigh" : {"img": "./img/goty2017/endisnigh.jpg", "info": "Platforms: "},
            "FIFA 18" : {"img": "./img/goty2017/fifa18.jpg", "info": "Platforms: "},
            "Puyo Puyo Tetris" : {"img": "./img/goty2017/puyotetris.jpg", "info": "Platforms: "},
            "The Sexy Brutale" : {"img": "./img/goty2017/sexybrutale.jpg", "info": "Platforms: "},
            "Little Nightmares" : {"img": "./img/goty2017/littlenightmares.jpg", "info": "Platforms: "}
  }
}
